language: java
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ant; fi
os:
  - osx
  - linux
matrix:
  include:
    - os: linux
      jdk: oraclejdk8